### ISSUE TITLE
Not showing errors on WSL

### ISSUE THREAD

**Issue by sanzoghenzo** [mxab/pre-commit-trivy#19]
Hi there!
I'm probably doing something wrong, but I can't get trivy error messages when running pre-commit (either via pre-commit run --all or actual pre-commit hook).

It outputs

```
trivyfs-docker...........................................................Failed
- hook id: trivyfs-docker
- exit code: 1
```

And nothing more.

This is my pre-commit config:

```yaml
repos:
  - repo: https://github.com/mxab/pre-commit-trivy.git
    rev: v0.12.0
    hooks:
      - id: trivyfs-docker
        args: [.]
      - id: trivyconfig-docker
        args: [.]
```

Using trivy, directly or via docker container, it correctly shows the errors.

I'm running it on Windows 10 inside an Ubuntu WSL.

Is there something I'm missing here?

Thanks for your attention
